"""Initial migration

Revision ID: f3b47f1ed93e
Revises:
Create Date: 2025-08-15 12:45:21.577038

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3b47f1ed93e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'wallets',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('address', sa.String(), nullable=True),
		sa.Column('balance', sa.Float(), nullable=False),
		sa.Column('bandwidth_free', sa.Integer(), nullable=False),
		sa.Column('bandwidth_by_staking', sa.Integer(), nullable=False),
		sa.Column('energy', sa.Integer(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('address'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('wallets')
	# ### end Alembic commands ###
